
======================================================================
testing event 'release-rpm'
----------------------------------------------------------------------
[release-rpm] runTest (test-modules.ReleaseRpmEventTestCase) ... ok
[release-rpm] runTest (test-modules.ReleaseRpmEventTestCase) ... ok
[release-rpm] runTest (test-modules.ReleaseRpmEventTestCase) ... ok
[release-rpm] runTest (test-modules.ReleaseRpmEventTestCase) ... ok
[release-rpm] runTest (test-modules.ReleaseRpmEventTestCase) ... ok
[release-rpm] runTest (test-modules.ReleaseRpmEventTestCase) ... ok
[release-rpm] runTest (test-modules.Test_ReleaseRpmInputs) ... ERROR
[release-rpm] runTest (test-modules.Test_ReleaseRpmBuild) ... ok
[release-rpm] runTest (test-modules.Test_ReleaseRpmCvars1) ... ok
[release-rpm] runTest (test-modules.Test_ReleaseRpmCvars2) ... ok
[release-rpm] runTest (test-modules.Test_RNotesExistence) ... ok


ERROR/FAILURE SUMMARY

======================================================================
[release-rpm] ERROR: runTest (test-modules.Test_ReleaseRpmInputs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/repos/spin-dev/spintest/modules/release-rpm.py", line 64, in runTest
    self.tb.dispatch.execute(until='release-rpm')
  File "/data/repos/rendition-common-dev/rendition/dispatch.py", line 157, in execute
    self._process('execute', until=until)
  File "/data/repos/rendition-common-dev/rendition/dispatch.py", line 165, in _process
    getattr(self.currevent, fn)(*args, **kwargs)
  File "/root/Workspace/spin-dev/spin/event/__init__.py", line 102, in execute
    self.setup()
  File "/root/Workspace/spin-dev/spin/modules/core/rpmbuild/release-rpm.py", line 91, in setup
    raise RuntimeError("release/eula.py not found in %s" % ', '.join(self.SHARE_DIRS))
RuntimeError: release/eula.py not found in /usr/share/spin

----------------------------------------------------------------------
ran 12 tests in 24.013s

FAILED (errors=1)
